In [78]:
%pip install pandas openpyxl

^C
Note: you may need to restart the kernel to use updated packages.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (3.0.5)
Requirement already satisfied: openpyxl in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import openpyxl

Libraries are ready

In [ ]:
file_path = "../data/TDS-MSDS.xlsx"

df = pd.read_excel(file_path, header=1)

df.head(20)

,Sl No.,Catagory Name,Product Name,TDS,MSDS
0,A,CEMENT ADDITIVES PRODUCT,NaN,NaN,NaN
1,1,Waterproofing Compounds,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,NaN
2,NaN,NaN,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,NaN
3,NaN,NaN,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,NaN
4,NaN,NaN,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,NaN
5,NaN,NaN,Hind Proof No – 2,https://www.hindcon.com/wp-content/uploads/202...,NaN
6,NaN,NaN,Hind Proof No – 3,https://www.hindcon.com/wp-content/uploads/202...,NaN
7,NaN,NaN,Hind Powder WP,https://www.hindcon.com/wp-content/uploads/202...,NaN
8,2,Concrete & Mortar Admixtures,Hind Flow Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
9,NaN,NaN,Hind Plast AEA,https://www.hindcon.com/wp-content/uploads/202...,NaN
10,NaN,NaN,Hind Plast AEP,https://www.hindcon.com/wp-content/uploads/202...,NaN
11,NaN,NaN,Hind Plast IWA,https://www.hindcon.com/wp-content/uploads/202...,NaN
12,NaN,NaN,Hind Plast N,https://www.hindcon.com/wp-content/uploads/202...,NaN
13,NaN,NaN,Hind Plast Super SCA-800,https://www.hindcon.com/wp-content/uploads/202...,NaN
14,NaN,NaN,Hind Plast Super M,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
15,NaN,NaN,Hind Plast Super 160 (P),https://www.hindcon.com/wp-content/uploads/202...,NaN
16,NaN,NaN,Hind Plast Super 160,https://www.hindcon.com/wp-content/uploads/202...,NaN
17,NaN,NaN,Hind Plast Super A,https://www.hindcon.com/wp-content/uploads/202...,NaN
18,NaN,NaN,Hind Plast Super Anti Freeze,https://www.hindcon.com/wp-content/uploads/202...,NaN
19,NaN,NaN,Hind Plast Super HPC 600,https://www.hindcon.com/wp-content/uploads/202...,NaN

In [ ]:
df["Catagory Name"] = df["Catagory Name"].ffill()

In [ ]:
df.head(100)

,Sl No.,Catagory Name,Product Name,TDS,MSDS
0,A,CEMENT ADDITIVES PRODUCT,NaN,NaN,NaN
1,1,Waterproofing Compounds,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,NaN
2,NaN,Waterproofing Compounds,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,NaN
3,NaN,Waterproofing Compounds,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,NaN
4,NaN,Waterproofing Compounds,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,NaN
...,...,...,...,...,...
95,NaN,Protective Coating & Sheeting,Hind Hydro Flex AQPU,https://www.hindcon.com/wp-content/uploads/202...,NaN
96,NaN,Protective Coating & Sheeting,Hind Hydroflex Polyurea (H),https://www.hindcon.com/wp-content/uploads/202...,NaN
97,NaN,Protective Coating & Sheeting,Hind Hydroflex Polyurea (P),https://www.hindcon.com/wp-content/uploads/202...,NaN
98,NaN,Protective Coating & Sheeting,Hind Hydro Shield SBS,https://www.hindcon.com/wp-content/uploads/202...,NaN
99,NaN,Protective Coating & Sheeting,Hind Hydro Shield,https://www.hindcon.com/wp-content/uploads/202...,NaN

In [ ]:
df = df[df["Product Name"].notna()].copy()

In [ ]:
df.head(50)

,Sl No.,Catagory Name,Product Name,TDS,MSDS
1,1,Waterproofing Compounds,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,NaN
2,NaN,Waterproofing Compounds,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,NaN
3,NaN,Waterproofing Compounds,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,NaN
4,NaN,Waterproofing Compounds,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,NaN
5,NaN,Waterproofing Compounds,Hind Proof No – 2,https://www.hindcon.com/wp-content/uploads/202...,NaN
6,NaN,Waterproofing Compounds,Hind Proof No – 3,https://www.hindcon.com/wp-content/uploads/202...,NaN
7,NaN,Waterproofing Compounds,Hind Powder WP,https://www.hindcon.com/wp-content/uploads/202...,NaN
8,2,Concrete & Mortar Admixtures,Hind Flow Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
9,NaN,Concrete & Mortar Admixtures,Hind Plast AEA,https://www.hindcon.com/wp-content/uploads/202...,NaN
10,NaN,Concrete & Mortar Admixtures,Hind Plast AEP,https://www.hindcon.com/wp-content/uploads/202...,NaN
11,NaN,Concrete & Mortar Admixtures,Hind Plast IWA,https://www.hindcon.com/wp-content/uploads/202...,NaN
12,NaN,Concrete & Mortar Admixtures,Hind Plast N,https://www.hindcon.com/wp-content/uploads/202...,NaN
13,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA-800,https://www.hindcon.com/wp-content/uploads/202...,NaN
14,NaN,Concrete & Mortar Admixtures,Hind Plast Super M,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
15,NaN,Concrete & Mortar Admixtures,Hind Plast Super 160 (P),https://www.hindcon.com/wp-content/uploads/202...,NaN
16,NaN,Concrete & Mortar Admixtures,Hind Plast Super 160,https://www.hindcon.com/wp-content/uploads/202...,NaN
17,NaN,Concrete & Mortar Admixtures,Hind Plast Super A,https://www.hindcon.com/wp-content/uploads/202...,NaN
18,NaN,Concrete & Mortar Admixtures,Hind Plast Super Anti Freeze,https://www.hindcon.com/wp-content/uploads/202...,NaN
19,NaN,Concrete & Mortar Admixtures,Hind Plast Super HPC 600,https://www.hindcon.com/wp-content/uploads/202...,NaN
20,NaN,Concrete & Mortar Admixtures,Hind Plast Super HPC,https://www.hindcon.com/wp-content/uploads/202...,NaN
21,NaN,Concrete & Mortar Admixtures,Hind Plast Super HR,https://www.hindcon.com/wp-content/uploads/202...,NaN
22,NaN,Concrete & Mortar Admixtures,Hind Plast Super MMF,https://www.hindcon.com/wp-content/uploads/202...,NaN
23,NaN,Concrete & Mortar Admixtures,Hind Plast Super P,https://www.hindcon.com/wp-content/uploads/202...,NaN
24,NaN,Concrete & Mortar Admixtures,Hind Plast Super PQC,https://www.hindcon.com/wp-content/uploads/202...,NaN
25,NaN,Concrete & Mortar Admixtures,Hind Plast Super R,https://www.hindcon.com/wp-content/uploads/202...,NaN
26,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA 100,https://www.hindcon.com/wp-content/uploads/202...,NaN
27,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA 1000,https://www.hindcon.com/wp-content/uploads/202...,NaN
28,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
29,NaN,Concrete & Mortar Admixtures,Hind Plast Super WRA,https://www.hindcon.com/wp-content/uploads/202...,NaN
30,NaN,Concrete & Mortar Admixtures,Hind Plast Super,https://www.hindcon.com/wp-content/uploads/202...,NaN
31,NaN,Concrete & Mortar Admixtures,Hind Plast VMA (L),https://www.hindcon.com/wp-content/uploads/202...,NaN
32,NaN,Concrete & Mortar Admixtures,Hind Plast VMA,https://www.hindcon.com/wp-content/uploads/202...,NaN
33,NaN,Concrete & Mortar Admixtures,Hind Quick Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
34,NaN,Concrete & Mortar Admixtures,Hind Flow Set 2000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
35,NaN,Concrete & Mortar Admixtures,Hind Quick Set 2000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
36,NaN,Concrete & Mortar Admixtures,Hind Plast Super HPC 300,https://www.hindcon.com/wp-content/uploads/202...,NaN
37,3,Concreting Aid,Hind Anti Air,https://www.hindcon.com/wp-content/uploads/202...,NaN
38,NaN,Concreting Aid,Hind Bond EBA,https://www.hindcon.com/wp-content/uploads/202...,NaN
39,NaN,Concreting Aid,Hind Cempox (M),https://www.hindcon.com/wp-content/uploads/202...,NaN
40,NaN,Concreting Aid,Hind Corroguard – SA,https://www.hindcon.com/wp-content/uploads/202...,NaN
41,NaN,Concreting Aid,Hind Corroguard,https://www.hindcon.com/wp-content/uploads/202...,NaN
42,NaN,Concreting Aid,Hind Cure AL,https://www.hindcon.com/wp-content/uploads/202...,NaN
43,NaN,Concreting Aid,Hind Cure APB,https://www.hindcon.com/wp-content/uploads/202...,NaN
44,NaN,Concreting Aid,Hind Cure APB (Clear),https://www.hindcon.com/wp-content/uploads/202...,NaN
45,NaN,Concreting Aid,Hind Cure APB (White),https://www.hindcon.com/wp-content/uploads/202...,NaN
46,NaN,Concreting Aid,Hind Cure SS,https://www.hindcon.com/wp-content/uploads/202...,NaN
47,NaN,Concreting Aid,Hind Cure WB,https://www.hindcon.com/wp-content/uploads/202...,NaN
48,NaN,Concreting Aid,Hind Cure WP,https://www.hindcon.com/wp-content/uploads/202...,NaN
49,NaN,Concreting Aid,Hind Easy Plast (E),https://www.hindcon.com/wp-content/uploads/202...,NaN
50,NaN,Concreting Aid,Hind Easy Plast (I),https://www.hindcon.com/wp-content/uploads/202...,NaN

In [ ]:
df = df.rename(columns={
    "Catagory Name": "Category"
})

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271 entries, 1 to 271
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sl No.        19 non-null     object
 1   Category      271 non-null    str
 2   Product Name  271 non-null    str
 3   TDS           270 non-null    str
 4   MSDS          18 non-null     str
 5   Product_ID    271 non-null    str
dtypes: object(1), str(5)
memory usage: 12.8+ KB

In [ ]:
df["Product_ID"] = ["HC" + str(i).zfill(3) for i in range(1, len(df) + 1)]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271 entries, 1 to 271
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sl No.        19 non-null     object
 1   Category      271 non-null    str
 2   Product Name  271 non-null    str
 3   TDS           270 non-null    str
 4   MSDS          18 non-null     str
 5   Product_ID    271 non-null    str
dtypes: object(1), str(5)
memory usage: 12.8+ KB

In [ ]:
df.head(50)

,Sl No.,Category,Product Name,TDS,MSDS,Product_ID
1,1,Waterproofing Compounds,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC001
2,NaN,Waterproofing Compounds,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC002
3,NaN,Waterproofing Compounds,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC003
4,NaN,Waterproofing Compounds,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC004
5,NaN,Waterproofing Compounds,Hind Proof No – 2,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC005
6,NaN,Waterproofing Compounds,Hind Proof No – 3,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC006
7,NaN,Waterproofing Compounds,Hind Powder WP,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC007
8,2,Concrete & Mortar Admixtures,Hind Flow Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...,HC008
9,NaN,Concrete & Mortar Admixtures,Hind Plast AEA,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC009
10,NaN,Concrete & Mortar Admixtures,Hind Plast AEP,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC010
11,NaN,Concrete & Mortar Admixtures,Hind Plast IWA,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC011
12,NaN,Concrete & Mortar Admixtures,Hind Plast N,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC012
13,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA-800,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC013
14,NaN,Concrete & Mortar Admixtures,Hind Plast Super M,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...,HC014
15,NaN,Concrete & Mortar Admixtures,Hind Plast Super 160 (P),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC015
16,NaN,Concrete & Mortar Admixtures,Hind Plast Super 160,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC016
17,NaN,Concrete & Mortar Admixtures,Hind Plast Super A,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC017
18,NaN,Concrete & Mortar Admixtures,Hind Plast Super Anti Freeze,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC018
19,NaN,Concrete & Mortar Admixtures,Hind Plast Super HPC 600,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC019
20,NaN,Concrete & Mortar Admixtures,Hind Plast Super HPC,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC020
21,NaN,Concrete & Mortar Admixtures,Hind Plast Super HR,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC021
22,NaN,Concrete & Mortar Admixtures,Hind Plast Super MMF,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC022
23,NaN,Concrete & Mortar Admixtures,Hind Plast Super P,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC023
24,NaN,Concrete & Mortar Admixtures,Hind Plast Super PQC,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC024
25,NaN,Concrete & Mortar Admixtures,Hind Plast Super R,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC025
26,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA 100,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC026
27,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA 1000,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC027
28,NaN,Concrete & Mortar Admixtures,Hind Plast Super SCA,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...,HC028
29,NaN,Concrete & Mortar Admixtures,Hind Plast Super WRA,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC029
30,NaN,Concrete & Mortar Admixtures,Hind Plast Super,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC030
31,NaN,Concrete & Mortar Admixtures,Hind Plast VMA (L),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC031
32,NaN,Concrete & Mortar Admixtures,Hind Plast VMA,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC032
33,NaN,Concrete & Mortar Admixtures,Hind Quick Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...,HC033
34,NaN,Concrete & Mortar Admixtures,Hind Flow Set 2000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...,HC034
35,NaN,Concrete & Mortar Admixtures,Hind Quick Set 2000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...,HC035
36,NaN,Concrete & Mortar Admixtures,Hind Plast Super HPC 300,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC036
37,3,Concreting Aid,Hind Anti Air,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC037
38,NaN,Concreting Aid,Hind Bond EBA,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC038
39,NaN,Concreting Aid,Hind Cempox (M),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC039
40,NaN,Concreting Aid,Hind Corroguard – SA,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC040
41,NaN,Concreting Aid,Hind Corroguard,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC041
42,NaN,Concreting Aid,Hind Cure AL,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC042
43,NaN,Concreting Aid,Hind Cure APB,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC043
44,NaN,Concreting Aid,Hind Cure APB (Clear),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC044
45,NaN,Concreting Aid,Hind Cure APB (White),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC045
46,NaN,Concreting Aid,Hind Cure SS,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC046
47,NaN,Concreting Aid,Hind Cure WB,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC047
48,NaN,Concreting Aid,Hind Cure WP,https://www.hindcon.com/wp-content/uploads/202...,NaN,HC048
49,NaN,Concreting Aid,Hind Easy Plast (E),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC049
50,NaN,Concreting Aid,Hind Easy Plast (I),https://www.hindcon.com/wp-content/uploads/202...,NaN,HC050

In [ ]:
df = df[
    ["Product_ID", "Category", "Product Name", "TDS", "MSDS"]
]

In [ ]:
df = df.rename(columns={
    "Product Name": "Product_Name",
    "TDS": "TDS_Link",
    "MSDS": "MSDS_Link"
})

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271 entries, 1 to 271
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    271 non-null    str
 1   Category      271 non-null    str
 2   Product_Name  271 non-null    str
 3   TDS_Link      270 non-null    str
 4   MSDS_Link     18 non-null     str
dtypes: str(5)
memory usage: 10.7 KB

In [ ]:
print(df.shape)
print(df.columns.tolist())

(271, 5)
['Product_ID', 'Category', 'Product_Name', 'TDS_Link', 'MSDS_Link']

In [ ]:
df.head(10)

,Product_ID,Category,Product_Name,TDS_Link,MSDS_Link
1,HC001,Waterproofing Compounds,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,NaN
2,HC002,Waterproofing Compounds,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,NaN
3,HC003,Waterproofing Compounds,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,NaN
4,HC004,Waterproofing Compounds,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,NaN
5,HC005,Waterproofing Compounds,Hind Proof No – 2,https://www.hindcon.com/wp-content/uploads/202...,NaN
6,HC006,Waterproofing Compounds,Hind Proof No – 3,https://www.hindcon.com/wp-content/uploads/202...,NaN
7,HC007,Waterproofing Compounds,Hind Powder WP,https://www.hindcon.com/wp-content/uploads/202...,NaN
8,HC008,Concrete & Mortar Admixtures,Hind Flow Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
9,HC009,Concrete & Mortar Admixtures,Hind Plast AEA,https://www.hindcon.com/wp-content/uploads/202...,NaN
10,HC010,Concrete & Mortar Admixtures,Hind Plast AEP,https://www.hindcon.com/wp-content/uploads/202...,NaN

In [ ]:
output_file = "../output/products_dataset.xlsx"

df.to_excel(output_file, index=False)

print("Dataset saved successfully!")
print(output_file)

Dataset saved successfully!
../output/products_dataset.xlsx

In [ ]:
file_path = "../output/products_dataset.xlsx"

df = pd.read_excel(file_path)

df.head(20)

,Product_ID,Category,Product_Name,TDS_Link,MSDS_Link
0,HC001,Waterproofing Compounds,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,NaN
1,HC002,Waterproofing Compounds,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,NaN
2,HC003,Waterproofing Compounds,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,NaN
3,HC004,Waterproofing Compounds,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,NaN
4,HC005,Waterproofing Compounds,Hind Proof No – 2,https://www.hindcon.com/wp-content/uploads/202...,NaN
5,HC006,Waterproofing Compounds,Hind Proof No – 3,https://www.hindcon.com/wp-content/uploads/202...,NaN
6,HC007,Waterproofing Compounds,Hind Powder WP,https://www.hindcon.com/wp-content/uploads/202...,NaN
7,HC008,Concrete & Mortar Admixtures,Hind Flow Set 1000,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
8,HC009,Concrete & Mortar Admixtures,Hind Plast AEA,https://www.hindcon.com/wp-content/uploads/202...,NaN
9,HC010,Concrete & Mortar Admixtures,Hind Plast AEP,https://www.hindcon.com/wp-content/uploads/202...,NaN
10,HC011,Concrete & Mortar Admixtures,Hind Plast IWA,https://www.hindcon.com/wp-content/uploads/202...,NaN
11,HC012,Concrete & Mortar Admixtures,Hind Plast N,https://www.hindcon.com/wp-content/uploads/202...,NaN
12,HC013,Concrete & Mortar Admixtures,Hind Plast Super SCA-800,https://www.hindcon.com/wp-content/uploads/202...,NaN
13,HC014,Concrete & Mortar Admixtures,Hind Plast Super M,https://www.hindcon.com/wp-content/uploads/202...,https://www.hindcon.com/wp-content/uploads/202...
14,HC015,Concrete & Mortar Admixtures,Hind Plast Super 160 (P),https://www.hindcon.com/wp-content/uploads/202...,NaN
15,HC016,Concrete & Mortar Admixtures,Hind Plast Super 160,https://www.hindcon.com/wp-content/uploads/202...,NaN
16,HC017,Concrete & Mortar Admixtures,Hind Plast Super A,https://www.hindcon.com/wp-content/uploads/202...,NaN
17,HC018,Concrete & Mortar Admixtures,Hind Plast Super Anti Freeze,https://www.hindcon.com/wp-content/uploads/202...,NaN
18,HC019,Concrete & Mortar Admixtures,Hind Plast Super HPC 600,https://www.hindcon.com/wp-content/uploads/202...,NaN
19,HC020,Concrete & Mortar Admixtures,Hind Plast Super HPC,https://www.hindcon.com/wp-content/uploads/202...,NaN

In [ ]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
Product_ID        0
Category          0
Product_Name      0
TDS_Link          1
MSDS_Link       253
dtype: int64

In [ ]:
missing_tds = df[df["TDS_Link"].isna()]

print(missing_tds[["Product_ID", "Category", "Product_Name"]])

    Product_ID                       Category       Product_Name
103      HC104  Protective Coating & Sheeting  Hind HydroFlex PU

In [ ]:
duplicates = df[df.duplicated("Product_Name", keep=False)]

print(duplicates[["Product_ID", "Category", "Product_Name"]])

    Product_ID                       Category         Product_Name
57       HC058                 Concreting Aid         Hind Patch R
71       HC072                 Concreting Aid    Hind Cure Hard 54
81       HC082  Protective Coating & Sheeting       Hind Anti Rust
104      HC105  Protective Coating & Sheeting    Hind Hydrolast 2K
105      HC106  Protective Coating & Sheeting    Hind Plasto Guard
108      HC109  Protective Coating & Sheeting      Hind Styrene BR
117      HC118  Protective Coating & Sheeting  Hind Crete Plus WPM
132      HC133                   Grouts (New)       Hind Geo Grout
137      HC138                   Grouts (New)       Hind Grout SST
139      HC140                   Grouts (New)      Hind Tile Grout
140      HC141                   Grouts (New)       Hind Plast EGA
184      HC185                       Flooring    Hind Cure Hard 54
204      HC205                        Sealant      Hind Sealant PS
221      HC222                 Tile Adhesives       Hind Block Fix
236      HC237                 Excavation Aid       Hind Geo Grout
237      HC238                 Excavation Aid       Hind Grout SST
241      HC242                 Green Products       Hind Anti Rust
242      HC243                 Green Products       Hind Block Fix
243      HC244                 Green Products  Hind Crete Plus WPM
247      HC248                 Green Products    Hind Hydrolast 2K
248      HC249                 Green Products         Hind Patch R
249      HC250                 Green Products       Hind Plast EGA
250      HC251                 Green Products    Hind Plasto Guard
251      HC252                 Green Products      Hind Sealant PS
252      HC253                 Green Products      Hind Styrene BR
253      HC254                 Green Products      Hind Tile Grout

In [ ]:
df["TDS_Status"] = df["TDS_Link"].apply(
    lambda x: "Available" if pd.notna(x) and str(x).strip() != "" else "Missing"
)

In [ ]:
print(df["TDS_Status"].value_counts())

TDS_Status
Available    270
Missing        1
Name: count, dtype: int64

In [ ]:
print(
    df[df["TDS_Status"] == "Missing"][
        ["Product_ID", "Category", "Product_Name"]
    ]
)

    Product_ID                       Category       Product_Name
103      HC104  Protective Coating & Sheeting  Hind HydroFlex PU

In [ ]:
first_tds = df.iloc[0]["TDS_Link"]

print("Product:", df.iloc[0]["Product_Name"])
print("TDS Link:", first_tds)

Product: Hind Crystel Seal
TDS Link: https://www.hindcon.com/wp-content/uploads/2025/02/HIND-CRYSTAL-SEAL_TDS-1.pdf

In [ ]:
print(type(first_tds))
print(first_tds)

<class 'str'>
https://www.hindcon.com/wp-content/uploads/2025/02/HIND-CRYSTAL-SEAL_TDS-1.pdf

In [ ]:
%pip install requests pypdf

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (2.34.2)
Collecting pypdf
  Downloading pypdf-6.18.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from requests) (2026.7.22)
Downloading pypdf-6.18.0-py3-none-any.whl (393 kB)
Installing collected packages: pypdf
Successfully installed pypdf-6.18.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import requests
import os

product_id = df.iloc[0]["Product_ID"]
product_name = df.iloc[0]["Product_Name"]
tds_url = df.iloc[0]["TDS_Link"]

print("Product:", product_name)
print("URL:", tds_url)

Product: Hind Crystel Seal
URL: https://www.hindcon.com/wp-content/uploads/2025/02/HIND-CRYSTAL-SEAL_TDS-1.pdf

In [ ]:
pdf_response = requests.get(tds_url, timeout=30)

print("Status code:", pdf_response.status_code)
print("File size:", len(pdf_response.content), "bytes")

Status code: 200
File size: 1502612 bytes

In [ ]:
os.makedirs("../tds_pdfs", exist_ok=True)

pdf_path = f"../tds_pdfs/{product_id}.pdf"

with open(pdf_path, "wb") as f:
    f.write(pdf_response.content)

print("PDF saved:", pdf_path)

PDF saved: ../tds_pdfs/HC001.pdf

In [ ]:
from pypdf import PdfReader

reader = PdfReader(pdf_path)

print("Number of pages:", len(reader.pages))

text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text + "\n"

print(text[:3000])

Number of pages: 2
HINDCON
CHEMICALS LTD.HIND CRYSTAL SEAL
DESCRIPTION
Hind Crystal Seal is a capillary waterprooﬁng formulation of proprietary blends of moisture active
chemicals, quartz, sand and cement. The chemical contained in Hind Crystal Seal formulations
requires the presence of moisture for the chemical reaction to take place and in combination with
the “free lime”, the chemical in Hind Crystal Seal forms long chain complexes which crystallizes
in the capillaries. It conforms to IS: 2645-2003 & ACI 212.3R - 10.
USES
Hind Crystal Seal protects concrete and mortar making it 100% waterproof. It improves the
adhesion between top coat and concrete or mortar. It is used for waterprooﬁng of water reservoir,
water tower, tunnels, dams, canals, concrete pipes, water treatment plant, sea wall, bridges and
decks etc.
ADVANTAGES
• Ready for use only by mixing with water.
• Can be applied on damp concrete surface with no standing water.
• Non-toxic and can be applied on Concrete storage tank used for potable water.
• Cost eﬀective waterprooﬁng system.
• The crystallization reaction between Hind Crystal Seal with free lime and Calcium hydroxide
in cement will form crystal to fully block the capillary in the concrete and mortar. It gives a total
and permanent waterprooﬁng to concrete structures in the presence of moisture.
• Can be applied to both positive and negative side protection of water retaining and
underground structures.
APPLICATION
It has to be ensured before application that all concrete and mortar surfaces are clean free from
dust, laitance, oil and grease. The surfaces to be pre-wetted, so that it is completely saturated.
Hind Crystal Seal is to be applied on damp surfaces and there should be no standing water. Hind
Crystal Seal 10kg (One bag) is to be mixed with 3-3.5 Litre of clean water for 3 (three) minutes
using a slow speed mechanical mixer (60 rpm) until a uniform homogenous mix is obtained. Use
brush or roller for application. We recommend 2 coats to be applied in interval of 3-4 hours to give
better results. Hind Crystal Seal is a cementitious based products, and the treated surface with
Hind Crystal Seal is to be properly cured by covering it with damp cover or moist curing for at
least 5-7 days. Hind Crystal Seal can be applied immediately on new concrete surface as soon
as the formwork has been removed.
CRYSTALLINE CAPILLARY WATERPROOFING FOR CONCRETE AND MORTAR.
contactus@hindcon.com +91 33 24490839, 9830599113 +91 33 24490849 Kolkata, West Bengal, India
Hindcon Chemicals maintains a team of technically trained professionals to provide full support to  your problems in construction, and
recommend the correct product to suite your specific requirements. Our authorized applicators can attend your site for application of the products.
The content of the Technical datasheet are for general information and guideline. The result shown here are generated from our laboratory or from
our site experiences.
HINDCON
CHEMICALS LTD.
I

In [ ]:
import requests
import os
import time
from pypdf import PdfReader

# Create folder for downloaded PDFs
os.makedirs("../tds_pdfs", exist_ok=True)

# List to store TDS information
tds_data = []

for index, row in df.iterrows():

    product_id = row["Product_ID"]
    product_name = row["Product_Name"]
    tds_url = row["TDS_Link"]

    print(f"Processing {product_id}: {product_name}")

    # Skip products without a TDS link
    if pd.isna(tds_url):
        tds_data.append({
            "Product_ID": product_id,
            "Product_Name": product_name,
            "TDS_Link": None,
            "TDS_Text": None,
            "Status": "TDS Link Missing"
        })
        continue

    try:
        # Download PDF
        response = requests.get(tds_url, timeout=30)
        response.raise_for_status()

        # Save PDF
        pdf_path = f"../tds_pdfs/{product_id}.pdf"

        with open(pdf_path, "wb") as f:
            f.write(response.content)

        # Extract PDF text
        reader = PdfReader(pdf_path)

        text = ""

        for page in reader.pages:
            page_text = page.extract_text()

            if page_text:
                text += page_text + "\n"

        # Store result
        tds_data.append({
            "Product_ID": product_id,
            "Product_Name": product_name,
            "TDS_Link": tds_url,
            "TDS_Text": text.strip(),
            "Status": "Success"
        })

        print("   ✓ Downloaded and extracted")

    except Exception as e:

        tds_data.append({
            "Product_ID": product_id,
            "Product_Name": product_name,
            "TDS_Link": tds_url,
            "TDS_Text": None,
            "Status": f"Error: {str(e)}"
        })

        print("   ✗ Error:", e)

    # Small delay between downloads
    time.sleep(0.5)

print("Finished processing all TDS files.")

Processing HC001: Hind Crystel Seal
   ✓ Downloaded and extracted
Processing HC002: Hind Crystel Seal (1)
   ✓ Downloaded and extracted
Processing HC003: Hind Plug - S
   ✓ Downloaded and extracted
Processing HC004: Hind Proof No – 1
   ✓ Downloaded and extracted
Processing HC005: Hind Proof No – 2
   ✓ Downloaded and extracted
Processing HC006: Hind Proof No – 3
   ✓ Downloaded and extracted
Processing HC007: Hind Powder WP
   ✓ Downloaded and extracted
Processing HC008: Hind Flow Set 1000
   ✓ Downloaded and extracted
Processing HC009: Hind Plast AEA
   ✓ Downloaded and extracted
Processing HC010: Hind Plast AEP
   ✓ Downloaded and extracted
Processing HC011: Hind Plast IWA
   ✓ Downloaded and extracted
Processing HC012: Hind Plast N
   ✓ Downloaded and extracted
Processing HC013: Hind Plast Super SCA-800
   ✓ Downloaded and extracted
Processing HC014: Hind Plast Super M
   ✓ Downloaded and extracted
Processing HC015: Hind Plast Super 160 (P)
   ✓ Downloaded and extracted
Processing HC016: Hind Plast Super 160
   ✓ Downloaded and extracted
Processing HC017: Hind Plast Super A
   ✓ Downloaded and extracted
Processing HC018: Hind Plast Super Anti Freeze
   ✓ Downloaded and extracted
Processing HC019: Hind Plast Super HPC 600
   ✓ Downloaded and extracted
Processing HC020: Hind Plast Super HPC
   ✓ Downloaded and extracted
Processing HC021: Hind Plast Super HR
   ✓ Downloaded and extracted
Processing HC022: Hind Plast Super MMF
   ✓ Downloaded and extracted
Processing HC023: Hind Plast Super P
   ✓ Downloaded and extracted
Processing HC024: Hind Plast Super PQC
   ✓ Downloaded and extracted
Processing HC025: Hind Plast Super R
   ✓ Downloaded and extracted
Processing HC026: Hind Plast Super SCA 100
   ✓ Downloaded and extracted
Processing HC027: Hind Plast Super SCA 1000
   ✓ Downloaded and extracted
Processing HC028: Hind Plast Super SCA
   ✓ Downloaded and extracted
Processing HC029: Hind Plast Super WRA
   ✓ Downloaded and extracted
Processing HC030: Hind Plast Super
   ✓ Downloaded and extracted
Processing HC031: Hind Plast VMA (L)
   ✓ Downloaded and extracted
Processing HC032: Hind Plast VMA
   ✓ Downloaded and extracted
Processing HC033: Hind Quick Set 1000
   ✓ Downloaded and extracted
Processing HC034: Hind Flow Set 2000
   ✓ Downloaded and extracted
Processing HC035: Hind Quick Set 2000
   ✓ Downloaded and extracted
Processing HC036: Hind Plast Super HPC 300
   ✓ Downloaded and extracted
Processing HC037: Hind Anti Air
   ✓ Downloaded and extracted
Processing HC038: Hind Bond EBA
   ✓ Downloaded and extracted
Processing HC039: Hind Cempox (M)
   ✓ Downloaded and extracted
Processing HC040: Hind Corroguard – SA
   ✓ Downloaded and extracted
Processing HC041: Hind Corroguard
   ✓ Downloaded and extracted
Processing HC042: Hind Cure AL
   ✓ Downloaded and extracted
Processing HC043: Hind Cure APB
   ✓ Downloaded and extracted
Processing HC044: Hind Cure APB (Clear)
   ✓ Downloaded and extracted
Processing HC045: Hind Cure APB (White)
   ✓ Downloaded and extracted
Processing HC046: Hind Cure SS
   ✓ Downloaded and extracted
Processing HC047: Hind Cure WB
   ✗ Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2025/05/HIND-CURE-WB_TDS.pdf
Processing HC048: Hind Cure WP
   ✓ Downloaded and extracted
Processing HC049: Hind Easy Plast (E)
   ✓ Downloaded and extracted
Processing HC050: Hind Easy Plast (I)
   ✓ Downloaded and extracted
Processing HC051: Hind Fiber Glass
   ✓ Downloaded and extracted
Processing HC052: Hind Foamex
   ✓ Downloaded and extracted
Processing HC053: Hind Insu Foam
   ✓ Downloaded and extracted
Processing HC054: Hind Mould Release OB
   ✓ Downloaded and extracted
Processing HC055: Hind Mould Release RTU
   ✓ Downloaded and extracted
Processing HC056: Hind Mould Release WT
   ✓ Downloaded and extracted
Processing HC057: Hind Patch M
   ✓ Downloaded and extracted
Processing HC058: Hind Patch R
   ✓ Downloaded and extracted
Processing HC059: Hind PO Fiber 55/65
   ✓ Downloaded and extracted
Processing HC060: Hind PO Fiber 55/78
   ✓ Downloaded and extracted
Processing HC061: Hind PP Fiber
   ✓ Downloaded and extracted
Processing HC062: Hind Pump Prime
   ✓ Downloaded and extracted
Processing HC063: Hind SBR Bond
   ✓ Downloaded and extracted
Processing HC064: Hind Silica M (S)
   ✓ Downloaded and extracted
Processing HC065: Hind Silica M
   ✓ Downloaded and extracted
Processing HC066: Hind Steel Fiber (FC)
   ✓ Downloaded and extracted
Processing HC067: Hind Steel Fiber (HK)
   ✓ Downloaded and extracted
Processing HC068: Hind Super Cure R
   ✓ Downloaded and extracted
Processing HC069: Hind Super FA
   ✓ Downloaded and extracted
Processing HC070: Hind Easy Plast (C)
   ✓ Downloaded and extracted
Processing HC071: Hind Patch R 80
   ✓ Downloaded and extracted
Processing HC072: Hind Cure Hard 54
   ✓ Downloaded and extracted
Processing HC073: Hind PU Foam
   ✓ Downloaded and extracted
Processing HC074: HIND MOULD RELEASE OB 742
   ✓ Downloaded and extracted
Processing HC075: Hind CS 30
   ✓ Downloaded and extracted
Processing HC076: Hind CS 40
   ✓ Downloaded and extracted
Processing HC077: Hind Silica M (92)
   ✓ Downloaded and extracted
Processing HC078: Hind Patch R 100
   ✓ Downloaded and extracted
Processing HC079: Hind Mould Release Form TR3
   ✓ Downloaded and extracted
Processing HC080: Hind Acrylic Wall Putty
   ✓ Downloaded and extracted
Processing HC081: Hind Anti Rust EZ
   ✓ Downloaded and extracted
Processing HC082: Hind Anti Rust
   ✓ Downloaded and extracted
Processing HC083: Hind Basebond
   ✓ Downloaded and extracted
Processing HC084: Hind Bitkote (CT)
   ✓ Downloaded and extracted
Processing HC085: Hind Bitkote
   ✓ Downloaded and extracted
Processing HC086: Hind Coat CTM
   ✓ Downloaded and extracted
Processing HC087: Hind Coat EP
   ✓ Downloaded and extracted
Processing HC088: Hind Coat PPU
   ✓ Downloaded and extracted
Processing HC089: Hind ERS 21 PC
   ✓ Downloaded and extracted
Processing HC090: Hind ERS WS
   ✓ Downloaded and extracted
Processing HC091: Hind Cool Coat (Formerly Hind Hydraproof Ceramic)
   ✓ Downloaded and extracted
Processing HC092: Hind Coat Repel
   ✓ Downloaded and extracted
Processing HC093: Hind Elasto Coat Formerly Hind Crete Plus WPM (E)
   ✗ Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2026/02/HIND-ELASTO-COAT-TDS.pdf
Processing HC094: Hind Hydro Proof
   ✓ Downloaded and extracted
Processing HC095: Hind Hydro Flex AQPU
   ✓ Downloaded and extracted
Processing HC096: Hind Hydroflex Polyurea (H)
   ✓ Downloaded and extracted
Processing HC097: Hind Hydroflex Polyurea (P)
   ✓ Downloaded and extracted
Processing HC098: Hind Hydro Shield SBS
   ✓ Downloaded and extracted
Processing HC099: Hind Hydro Shield
   ✓ Downloaded and extracted
Processing HC100: Hind HydroFlex PU 300
   ✓ Downloaded and extracted
Processing HC101: Hind HydroFlex PU(E)
   ✓ Downloaded and extracted
Processing HC102: Hind Hydro Flex PU (SB)
   ✓ Downloaded and extracted
Processing HC103: Hind Hydroshield PVC
   ✓ Downloaded and extracted
Processing HC104: Hind HydroFlex PU
Processing HC105: Hind Hydrolast 2K
   ✓ Downloaded and extracted
Processing HC106: Hind Plasto Guard
   ✓ Downloaded and extracted
Processing HC107: Hind Marine Cote
   ✓ Downloaded and extracted
Processing HC108: Hind Paver Cote
   ✓ Downloaded and extracted
Processing HC109: Hind Styrene BR
   ✓ Downloaded and extracted
Processing HC110: Hind Prime PU
   ✓ Downloaded and extracted
Processing HC111: Hind Seal Cote
   ✓ Downloaded and extracted
Processing HC112: Hind Crete Plus WPM E (RTU)
   ✓ Downloaded and extracted
Processing HC113: Hind Tile Cote
   ✓ Downloaded and extracted
Processing HC114: Hind Wall Putty
   ✓ Downloaded and extracted
Processing HC115: Hind Hydrolast HP (2K)
   ✓ Downloaded and extracted
Processing HC116: Hind Hydroflex Polyurea
   ✓ Downloaded and extracted
Processing HC117: Hind Hydroflex AQPU (Primer)
   ✓ Downloaded and extracted
Processing HC118: Hind Crete Plus WPM
   ✓ Downloaded and extracted
Processing HC119: Hind Hydro Flex PU 200
   ✓ Downloaded and extracted
Processing HC120: Hind Hydroflex WBPU
   ✓ Downloaded and extracted
Processing HC121: Hind Hydroshield PE
   ✓ Downloaded and extracted
Processing HC122: Hind EP Prime 800
   ✓ Downloaded and extracted
Processing HC123: Hind Hydroflex Polyurea (H 70)
   ✓ Downloaded and extracted
Processing HC124: Hind Hydroflex WBPU 2K
   ✓ Downloaded and extracted
Processing HC125: Hind Hydroflex Polyurea (H90)
   ✓ Downloaded and extracted
Processing HC126: Hind Urethane TC
   ✓ Downloaded and extracted
Processing HC127: Hind Hydro Flex PU (BM)
   ✓ Downloaded and extracted
Processing HC128: Hind Coat LR 9415
   ✓ Downloaded and extracted
Processing HC129: Hind Prime BIT 746
   ✓ Downloaded and extracted
Processing HC130: Hind Coat Repel SC
   ✓ Downloaded and extracted
Processing HC131: Hind PU CLX 650
   ✓ Downloaded and extracted
Processing HC132: Hind Carbo Guard W
   ✓ Downloaded and extracted
Processing HC133: Hind Geo Grout
   ✓ Downloaded and extracted
Processing HC134: Hind Grout GP2
   ✓ Downloaded and extracted
Processing HC135: Hind Grout GP
   ✓ Downloaded and extracted
Processing HC136: Hind Grout GP1
   ✓ Downloaded and extracted
Processing HC137: Hind Hydrafoam PU (SC)
   ✓ Downloaded and extracted
Processing HC138: Hind Grout SST
   ✓ Downloaded and extracted
Processing HC139: Hind HSMC
   ✓ Downloaded and extracted
Processing HC140: Hind Tile Grout
   ✓ Downloaded and extracted
Processing HC141: Hind Plast EGA
   ✓ Downloaded and extracted
Processing HC142: Hind Plast Super G
   ✓ Downloaded and extracted
Processing HC143: Hind Grout GP2 (M)
   ✓ Downloaded and extracted
Processing HC144: Hind Hydrafoam PU(2K)
   ✓ Downloaded and extracted
Processing HC145: Hind Grout PGM
   ✓ Downloaded and extracted
Processing HC146: Hind Power Grout
   ✓ Downloaded and extracted
Processing HC147: Hind Grout PGM (M)
   ✓ Downloaded and extracted
Processing HC148: Hind Anchorlok
   ✓ Downloaded and extracted
Processing HC149: Hind EP 21
   ✓ Downloaded and extracted
Processing HC150: Hind EP 321
   ✓ Downloaded and extracted
Processing HC151: Hind ERA 31
   ✓ Downloaded and extracted
Processing HC152: Hind ERS (UL)
   ✓ Downloaded and extracted
Processing HC153: Hind ERS 21 (LV)
   ✓ Downloaded and extracted
Processing HC154: Hind ERS 21
   ✓ Downloaded and extracted
Processing HC155: Hind ERS 21 P
   ✓ Downloaded and extracted
Processing HC156: Hind ERS 31 (LV)
   ✓ Downloaded and extracted
Processing HC157: Hind ERS 212
   ✓ Downloaded and extracted
Processing HC158: Hind ERS 216 (UV)
   ✓ Downloaded and extracted
Processing HC159: Hind ERS 219
   ✓ Downloaded and extracted
Processing HC160: Hind ERS-2115/2118/2120
   ✓ Downloaded and extracted
Processing HC161: Hind ERS 3116
   ✓ Downloaded and extracted
Processing HC162: Hind Marbo Cote 41
   ✓ Downloaded and extracted
Processing HC163: Hind EPC SLRH
   ✓ Downloaded and extracted
Processing HC164: Hind ERS (UL-F)
   ✓ Downloaded and extracted
Processing HC165: Hind ERS UL 800
   ✓ Downloaded and extracted
Processing HC166: Hind EP Coat 236
   ✓ Downloaded and extracted
Processing HC167: Hind EPZ 107
   ✓ Downloaded and extracted
Processing HC168: Hind CE 750
   ✓ Downloaded and extracted
Processing HC169: Hind Actcolor
   ✓ Downloaded and extracted
Processing HC170: Hind Coat FC
   ✓ Downloaded and extracted
Processing HC171: Hind Coat Prime
   ✓ Downloaded and extracted
Processing HC172: Hind Emetop M (RTU)
   ✓ Downloaded and extracted
Processing HC173: Hind Emetop M
   ✓ Downloaded and extracted
Processing HC174: Hind Emetop NM
   ✓ Downloaded and extracted
Processing HC175: Hind Emetop RTU
   ✓ Downloaded and extracted
Processing HC176: Hind FLC E
   ✓ Downloaded and extracted
Processing HC177: Hind FLC EUV
   ✓ Downloaded and extracted
Processing HC178: Hind Floor FLC
   ✓ Downloaded and extracted
Processing HC179: Hind Floortop
   ✓ Downloaded and extracted
Processing HC180: Hind Pentro Hard LH
   ✓ Downloaded and extracted
Processing HC181: Hind Polycoat
   ✓ Downloaded and extracted
Processing HC182: Hind Selfloor 1000 EPSL
   ✓ Downloaded and extracted
Processing HC183: Hind Selfloor 1000
   ✓ Downloaded and extracted
Processing HC184: Hind Pentro Hard NS
   ✓ Downloaded and extracted
Processing HC185: Hind Cure Hard 54
   ✓ Downloaded and extracted
Processing HC186: Hind ERS HBC
   ✓ Downloaded and extracted
Processing HC187: Hind Selfloor 2000
   ✓ Downloaded and extracted
Processing HC188: HIND ERS PRIME
   ✓ Downloaded and extracted
Processing HC189: Hind Bolt C
   ✓ Downloaded and extracted
Processing HC190: Hind Bolt R (Slow Set)
   ✓ Downloaded and extracted
Processing HC191: Hind Bolt R
   ✓ Downloaded and extracted
Processing HC192: Hind Cem (MF)
   ✓ Downloaded and extracted
Processing HC193: Hind Set LAF 100
   ✗ Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2025/07/HIND-SET-LAF-100.pdf
Processing HC194: Hind Set LAF
   ✓ Downloaded and extracted
Processing HC195: Hind Set PAF
   ✓ Downloaded and extracted
Processing HC196: Hind Shot Set L
   ✓ Downloaded and extracted
Processing HC197: Hind Shot Set P
   ✓ Downloaded and extracted
Processing HC198: Hind Set RP (AF)
   ✓ Downloaded and extracted
Processing HC199: Hind Sealant BP (HA)
   ✓ Downloaded and extracted
Processing HC200: Hind Sealant BP (HA-FR)
   ✓ Downloaded and extracted
Processing HC201: Hind Sealant BP
   ✓ Downloaded and extracted
Processing HC202: Hind Sealant E
   ✗ Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2026/05/HIND-SEALANT-E.pdf
Processing HC203: Hind Sealant.PPU
   ✓ Downloaded and extracted
Processing HC204: Hind Sealant Primer
   ✓ Downloaded and extracted
Processing HC205: Hind Sealant PS
   ✓ Downloaded and extracted
Processing HC206: Hind Sealant PU 125
   ✓ Downloaded and extracted
Processing HC207: Hind Sealant PU
   ✓ Downloaded and extracted
Processing HC208: Hind Silicone Sealant
   ✓ Downloaded and extracted
Processing HC209: Hind Sealant PU-PG (2K)
   ✓ Downloaded and extracted
Processing HC210: Hind Sealant PU 160
   ✓ Downloaded and extracted
Processing HC211: Hind PU Sealer 275
   ✓ Downloaded and extracted
Processing HC212: Hind ME Seal
   ✓ Downloaded and extracted
Processing HC213: Hind Silicone Sealant WP 200
   ✓ Downloaded and extracted
Processing HC214: Hind Silicone Sealant WP 800
   ✓ Downloaded and extracted
Processing HC215: Hind Concap CP 400
   ✓ Downloaded and extracted
Processing HC216: Hind Crack Seal 400
   ✓ Downloaded and extracted
Processing HC217: Hind MS 9215
   ✓ Downloaded and extracted
Processing HC218: Hind Sealant PU 100
   ✓ Downloaded and extracted
Processing HC219: Hind Sealant PU FLEX 825
   ✓ Downloaded and extracted
Processing HC220: Hind MS 40
   ✓ Downloaded and extracted
Processing HC221: Hind Seal BIT 1706
   ✓ Downloaded and extracted
Processing HC222: Hind Block Fix
   ✓ Downloaded and extracted
Processing HC223: Hind Fix MA (W)
   ✓ Downloaded and extracted
Processing HC224: Hind Fix TA (L)
   ✓ Downloaded and extracted
Processing HC225: Hind Fix TA (O)
   ✓ Downloaded and extracted
Processing HC226: Hind Fix TA – 1
   ✓ Downloaded and extracted
Processing HC227: Hind Fix TA – 2
   ✓ Downloaded and extracted
Processing HC228: Hind Grout Admix 737
   ✓ Downloaded and extracted
Processing HC229: Hind Fix TA – 3
   ✓ Downloaded and extracted
Processing HC230: Hind PU Masterflex
   ✓ Downloaded and extracted
Processing HC231: Hind Grout Admix 747
   ✓ Downloaded and extracted
Processing HC232: Hind Floor Cleaner (Neutral)
   ✓ Downloaded and extracted
Processing HC233: Hind Rust Clean
   ✓ Downloaded and extracted
Processing HC234: Hind Tile Clean
   ✓ Downloaded and extracted
Processing HC235: Hind MUltisafe Glass & Surface Cleaner
   ✓ Downloaded and extracted
Processing HC236: Hind Foundry SL
   ✓ Downloaded and extracted
Processing HC237: Hind Geo Grout
   ✓ Downloaded and extracted
Processing HC238: Hind Grout SST
   ✓ Downloaded and extracted
Processing HC239: Hind Poly Bond
   ✓ Downloaded and extracted
Processing HC240: Hind Hydroswell
   ✓ Downloaded and extracted
Processing HC241: Hind Injecto Tube
   ✓ Downloaded and extracted
Processing HC242: Hind Anti Rust
   ✓ Downloaded and extracted
Processing HC243: Hind Block Fix
   ✓ Downloaded and extracted
Processing HC244: Hind Crete Plus WPM
   ✓ Downloaded and extracted
Processing HC245: Hind Crystal Seal
   ✓ Downloaded and extracted
Processing HC246: Hind Fix TA
   ✓ Downloaded and extracted
Processing HC247: Hind Cool Coat (formerly Hind Hydraproof Ceramic)
   ✓ Downloaded and extracted
Processing HC248: Hind Hydrolast 2K
   ✓ Downloaded and extracted
Processing HC249: Hind Patch R
   ✓ Downloaded and extracted
Processing HC250: Hind Plast EGA
   ✓ Downloaded and extracted
Processing HC251: Hind Plasto Guard
   ✓ Downloaded and extracted
Processing HC252: Hind Sealant PS
   ✓ Downloaded and extracted
Processing HC253: Hind Styrene BR
   ✓ Downloaded and extracted
Processing HC254: Hind Tile Grout
   ✓ Downloaded and extracted
Processing HC255: Hind Grind Aid 400/450/500
   ✓ Downloaded and extracted
Processing HC256: Hind Emulsion A-C-P
   ✓ Downloaded and extracted
Processing HC257: Hind Sol SR
   ✓ Downloaded and extracted
Processing HC258: SODIUM SILICATE (NEUTRAL)
   ✓ Downloaded and extracted
Processing HC259: SODIUM SILICATE (ALKALINE)
   ✓ Downloaded and extracted
Processing HC260: COLLOIDAL SILICA (CS30)
   ✓ Downloaded and extracted
Processing HC261: COLLOIDAL SILICA (CS40)
   ✓ Downloaded and extracted
Processing HC262: SODIUM METASILICATE 5H₂O
   ✓ Downloaded and extracted
Processing HC263: SODIUM METASILICATE 9H₂O
   ✓ Downloaded and extracted
Processing HC264: Multi Safe FLOOR CLEANER (Lavender)
   ✗ Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?
Processing HC265: Multi Safe FLOOR CLEANER (Citrus)
   ✗ Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?
Processing HC266: Multi Safe FLOOR CLEANER (Floral)
   ✗ Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?
Processing HC267: Multi Safe FLOOR CLEANER (Neem)
   ✗ Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?
Processing HC268: Multi Safe TILE CLEANER
   ✗ Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?
Processing HC269: Multi Safe GLASS CLEANER
   ✗ Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?
Processing HC270: Multi Safe RUST REMOVER
   ✓ Downloaded and extracted
Processing HC271: Multi Safe TAP & SHOWER CLEANER
   ✓ Downloaded and extracted
Finished processing all TDS files.

In [ ]:
tds_df = pd.DataFrame(tds_data)

print(tds_df.shape)
print(tds_df["Status"].value_counts())

(271, 5)
Status
Success                                                                                                                    260
Error: Invalid URL 'TDS not found': No scheme supplied. Perhaps you meant https://TDS not found?                             6
Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2025/05/HIND-CURE-WB_TDS.pdf          1
Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2026/02/HIND-ELASTO-COAT-TDS.pdf      1
TDS Link Missing                                                                                                             1
Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2025/07/HIND-SET-LAF-100.pdf          1
Error: 404 Client Error: Not Found for url: https://www.hindcon.com/wp-content/uploads/2026/05/HIND-SEALANT-E.pdf            1
Name: count, dtype: int64

In [ ]:
import re

def clean_text_for_excel(text):
    if pd.isna(text):
        return text

    text = str(text)

    # Remove characters that Excel does not allow
    text = re.sub(r'[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]', '', text)

    return text

In [ ]:
tds_df["TDS_Text"] = tds_df["TDS_Text"].apply(clean_text_for_excel)

In [ ]:
import os

os.makedirs("../output", exist_ok=True)

tds_output = "../output/tds_dataset.xlsx"

tds_df.to_excel(tds_output, index=False)

print("TDS dataset saved successfully!")
print("Location:", tds_output)

TDS dataset saved successfully!
Location: ../output/tds_dataset.xlsx

In [ ]:
print("File exists:", os.path.exists(tds_output))
print("Rows:", len(tds_df))
print("Columns:", tds_df.columns.tolist())

File exists: True
Rows: 271
Columns: ['Product_ID', 'Product_Name', 'TDS_Link', 'TDS_Text', 'Status']

In [ ]:
file_path_tds_output = "../output/tds_dataset.xlsx"

In [ ]:
df_tds_text =pd.read_excel(file_path_tds_output)

In [ ]:
df_tds_text.head()

,Product_ID,Product_Name,TDS_Link,TDS_Text,Status
0,HC001,Hind Crystel Seal,https://www.hindcon.com/wp-content/uploads/202...,HINDCON\nCHEMICALS LTD.HIND CRYSTAL SEAL\nDESC...,Success
1,HC002,Hind Crystel Seal (1),https://www.hindcon.com/wp-content/uploads/202...,HINDCON\nCHEMICALS LTD.HIND CRYSTAL SEAL (I)\n...,Success
2,HC003,Hind Plug - S,https://www.hindcon.com/wp-content/uploads/202...,HINDCONCHEMICALS LTD.\nHIND PLUG - S \nDESCRIP...,Success
3,HC004,Hind Proof No – 1,https://www.hindcon.com/wp-content/uploads/202...,HINDCON\nCHEMICALS LTD.HIND PROOF NO-1 \nDESCR...,Success
4,HC005,Hind Proof No – 2,https://www.hindcon.com/wp-content/uploads/202...,HINDCON\nCHEMICALS LTD.HIND PROOF NO-2\nDESCRI...,Success

In [ ]:
import os

os.makedirs("../msds_pdfs", exist_ok=True)

print("MSDS folder created successfully!")

MSDS folder created successfully!

In [ ]:
import requests
from pypdf import PdfReader

msds_test = df[df["MSDS_Link"].notna()].iloc[0]

print("Product ID:", msds_test["Product_ID"])
print("Product Name:", msds_test["Product_Name"])
print("MSDS Link:", msds_test["MSDS_Link"])

response = requests.get(msds_test["MSDS_Link"], timeout=30)
response.raise_for_status()

test_path = f"../msds_pdfs/{msds_test['Product_ID']}.pdf"

with open(test_path, "wb") as f:
    f.write(response.content)

reader = PdfReader(test_path)

print("Number of pages:", len(reader.pages))

text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text + "\n"

print(text[:5000])

Product ID: HC008
Product Name: Hind Flow Set 1000
MSDS Link: https://www.hindcon.com/wp-content/uploads/2026/05/MSDS-for-Hind-Flow-Set-1000.pdf
Number of pages: 3
HINDCON
CHEMICALS LTD.
+91 33 24490839, 9830599113          contactus@hindcon           .comwww. .comhindcon
GST NO-19AAACH8021M1ZE      CIN: L24117WB1998PLC087800      UDYAM: WB-10-0004006
MATERIAL SAFETY DATA SHEET
HINDCON
CHEMICALS LTD.
+91 33 24490839, 9830599113          contactus@hindcon           .comwww. .comhindcon
GST NO-19AAACH8021M1ZE      CIN: L24117WB1998PLC087800      UDYAM: WB-10-0004006
HINDCON
CHEMICALS LTD.
+91 33 24490839, 9830599113          contactus@hindcon           .comwww. .comhindcon
GST NO-19AAACH8021M1ZE      CIN: L24117WB1998PLC087800      UDYAM: WB-10-0004006

In [ ]:
import requests
import os
import time
import pandas as pd
from pypdf import PdfReader

# Create folder
os.makedirs("../msds_pdfs", exist_ok=True)

msds_data = []

for index, row in df.iterrows():

    product_id = row["Product_ID"]
    product_name = row["Product_Name"]
    msds_url = row["MSDS_Link"]

    print(f"Processing {product_id}: {product_name}")

    # If MSDS link is missing
    if pd.isna(msds_url) or str(msds_url).strip() == "":
        msds_data.append({
            "Product_ID": product_id,
            "Product_Name": product_name,
            "MSDS_Link": None,
            "MSDS_Text": None,
            "Status": "MSDS Link Missing"
        })

        print("   - MSDS link missing")
        continue

    try:
        # Download PDF
        response = requests.get(msds_url, timeout=30)
        response.raise_for_status()

        # Save PDF
        pdf_path = f"../msds_pdfs/{product_id}.pdf"

        with open(pdf_path, "wb") as f:
            f.write(response.content)

        # Extract text
        reader = PdfReader(pdf_path)

        text = ""

        for page in reader.pages:
            page_text = page.extract_text()

            if page_text:
                text += page_text + "\n"

        msds_data.append({
            "Product_ID": product_id,
            "Product_Name": product_name,
            "MSDS_Link": msds_url,
            "MSDS_Text": text.strip(),
            "Status": "Success"
        })

        print("   ✓ Downloaded and extracted")

    except Exception as e:

        msds_data.append({
            "Product_ID": product_id,
            "Product_Name": product_name,
            "MSDS_Link": msds_url,
            "MSDS_Text": None,
            "Status": f"Error: {str(e)}"
        })

        print("   ✗ Error:", e)

    # Small delay so we don't send requests too quickly
    time.sleep(0.5)

print("\nFinished processing all MSDS files.")

Processing HC001: Hind Crystel Seal
   - MSDS link missing
Processing HC002: Hind Crystel Seal (1)
   - MSDS link missing
Processing HC003: Hind Plug - S
   - MSDS link missing
Processing HC004: Hind Proof No – 1
   - MSDS link missing
Processing HC005: Hind Proof No – 2
   - MSDS link missing
Processing HC006: Hind Proof No – 3
   - MSDS link missing
Processing HC007: Hind Powder WP
   - MSDS link missing
Processing HC008: Hind Flow Set 1000
   ✓ Downloaded and extracted
Processing HC009: Hind Plast AEA
   - MSDS link missing
Processing HC010: Hind Plast AEP
   - MSDS link missing
Processing HC011: Hind Plast IWA
   - MSDS link missing
Processing HC012: Hind Plast N
   - MSDS link missing
Processing HC013: Hind Plast Super SCA-800
   - MSDS link missing
Processing HC014: Hind Plast Super M
   ✓ Downloaded and extracted
Processing HC015: Hind Plast Super 160 (P)
   - MSDS link missing
Processing HC016: Hind Plast Super 160
   - MSDS link missing
Processing HC017: Hind Plast Super A
   - MSDS link missing
Processing HC018: Hind Plast Super Anti Freeze
   - MSDS link missing
Processing HC019: Hind Plast Super HPC 600
   - MSDS link missing
Processing HC020: Hind Plast Super HPC
   - MSDS link missing
Processing HC021: Hind Plast Super HR
   - MSDS link missing
Processing HC022: Hind Plast Super MMF
   - MSDS link missing
Processing HC023: Hind Plast Super P
   - MSDS link missing
Processing HC024: Hind Plast Super PQC
   - MSDS link missing
Processing HC025: Hind Plast Super R
   - MSDS link missing
Processing HC026: Hind Plast Super SCA 100
   - MSDS link missing
Processing HC027: Hind Plast Super SCA 1000
   - MSDS link missing
Processing HC028: Hind Plast Super SCA
   ✓ Downloaded and extracted
Processing HC029: Hind Plast Super WRA
   - MSDS link missing
Processing HC030: Hind Plast Super
   - MSDS link missing
Processing HC031: Hind Plast VMA (L)
   - MSDS link missing
Processing HC032: Hind Plast VMA
   - MSDS link missing
Processing HC033: Hind Quick Set 1000
   ✓ Downloaded and extracted
Processing HC034: Hind Flow Set 2000
   ✓ Downloaded and extracted
Processing HC035: Hind Quick Set 2000
   ✓ Downloaded and extracted
Processing HC036: Hind Plast Super HPC 300
   - MSDS link missing
Processing HC037: Hind Anti Air
   - MSDS link missing
Processing HC038: Hind Bond EBA
   - MSDS link missing
Processing HC039: Hind Cempox (M)
   - MSDS link missing
Processing HC040: Hind Corroguard – SA
   - MSDS link missing
Processing HC041: Hind Corroguard
   - MSDS link missing
Processing HC042: Hind Cure AL
   - MSDS link missing
Processing HC043: Hind Cure APB
   - MSDS link missing
Processing HC044: Hind Cure APB (Clear)
   - MSDS link missing
Processing HC045: Hind Cure APB (White)
   - MSDS link missing
Processing HC046: Hind Cure SS
   - MSDS link missing
Processing HC047: Hind Cure WB
   - MSDS link missing
Processing HC048: Hind Cure WP
   - MSDS link missing
Processing HC049: Hind Easy Plast (E)
   - MSDS link missing
Processing HC050: Hind Easy Plast (I)
   - MSDS link missing
Processing HC051: Hind Fiber Glass
   - MSDS link missing
Processing HC052: Hind Foamex
   - MSDS link missing
Processing HC053: Hind Insu Foam
   - MSDS link missing
Processing HC054: Hind Mould Release OB
   - MSDS link missing
Processing HC055: Hind Mould Release RTU
   - MSDS link missing
Processing HC056: Hind Mould Release WT
   - MSDS link missing
Processing HC057: Hind Patch M
   - MSDS link missing
Processing HC058: Hind Patch R
   - MSDS link missing
Processing HC059: Hind PO Fiber 55/65
   - MSDS link missing
Processing HC060: Hind PO Fiber 55/78
   - MSDS link missing
Processing HC061: Hind PP Fiber
   - MSDS link missing
Processing HC062: Hind Pump Prime
   ✓ Downloaded and extracted
Processing HC063: Hind SBR Bond
   - MSDS link missing
Processing HC064: Hind Silica M (S)
   - MSDS link missing
Processing HC065: Hind Silica M
   - MSDS link missing
Processing HC066: Hind Steel Fiber (FC)
   - MSDS link missing
Processing HC067: Hind Steel Fiber (HK)
   - MSDS link missing
Processing HC068: Hind Super Cure R
   - MSDS link missing
Processing HC069: Hind Super FA
   - MSDS link missing
Processing HC070: Hind Easy Plast (C)
   - MSDS link missing
Processing HC071: Hind Patch R 80
   - MSDS link missing
Processing HC072: Hind Cure Hard 54
   - MSDS link missing
Processing HC073: Hind PU Foam
   - MSDS link missing
Processing HC074: HIND MOULD RELEASE OB 742
   - MSDS link missing
Processing HC075: Hind CS 30
   - MSDS link missing
Processing HC076: Hind CS 40
   - MSDS link missing
Processing HC077: Hind Silica M (92)
   - MSDS link missing
Processing HC078: Hind Patch R 100
   - MSDS link missing
Processing HC079: Hind Mould Release Form TR3
   - MSDS link missing
Processing HC080: Hind Acrylic Wall Putty
   - MSDS link missing
Processing HC081: Hind Anti Rust EZ
   - MSDS link missing
Processing HC082: Hind Anti Rust
   - MSDS link missing
Processing HC083: Hind Basebond
   - MSDS link missing
Processing HC084: Hind Bitkote (CT)
   - MSDS link missing
Processing HC085: Hind Bitkote
   - MSDS link missing
Processing HC086: Hind Coat CTM
   - MSDS link missing
Processing HC087: Hind Coat EP
   - MSDS link missing
Processing HC088: Hind Coat PPU
   - MSDS link missing
Processing HC089: Hind ERS 21 PC
   ✓ Downloaded and extracted
Processing HC090: Hind ERS WS
   - MSDS link missing
Processing HC091: Hind Cool Coat (Formerly Hind Hydraproof Ceramic)
   - MSDS link missing
Processing HC092: Hind Coat Repel
   - MSDS link missing
Processing HC093: Hind Elasto Coat Formerly Hind Crete Plus WPM (E)
   ✓ Downloaded and extracted
Processing HC094: Hind Hydro Proof
   - MSDS link missing
Processing HC095: Hind Hydro Flex AQPU
   - MSDS link missing
Processing HC096: Hind Hydroflex Polyurea (H)
   - MSDS link missing
Processing HC097: Hind Hydroflex Polyurea (P)
   - MSDS link missing
Processing HC098: Hind Hydro Shield SBS
   - MSDS link missing
Processing HC099: Hind Hydro Shield
   - MSDS link missing
Processing HC100: Hind HydroFlex PU 300
   - MSDS link missing
Processing HC101: Hind HydroFlex PU(E)
   - MSDS link missing
Processing HC102: Hind Hydro Flex PU (SB)
   - MSDS link missing
Processing HC103: Hind Hydroshield PVC
   - MSDS link missing
Processing HC104: Hind HydroFlex PU
   - MSDS link missing
Processing HC105: Hind Hydrolast 2K
   - MSDS link missing
Processing HC106: Hind Plasto Guard
   - MSDS link missing
Processing HC107: Hind Marine Cote
   - MSDS link missing
Processing HC108: Hind Paver Cote
   ✓ Downloaded and extracted
Processing HC109: Hind Styrene BR
   - MSDS link missing
Processing HC110: Hind Prime PU
   - MSDS link missing
Processing HC111: Hind Seal Cote
   - MSDS link missing
Processing HC112: Hind Crete Plus WPM E (RTU)
   - MSDS link missing
Processing HC113: Hind Tile Cote
   - MSDS link missing
Processing HC114: Hind Wall Putty
   - MSDS link missing
Processing HC115: Hind Hydrolast HP (2K)
   - MSDS link missing
Processing HC116: Hind Hydroflex Polyurea
   - MSDS link missing
Processing HC117: Hind Hydroflex AQPU (Primer)
   - MSDS link missing
Processing HC118: Hind Crete Plus WPM
   - MSDS link missing
Processing HC119: Hind Hydro Flex PU 200
   - MSDS link missing
Processing HC120: Hind Hydroflex WBPU
   - MSDS link missing
Processing HC121: Hind Hydroshield PE
   - MSDS link missing
Processing HC122: Hind EP Prime 800
   - MSDS link missing
Processing HC123: Hind Hydroflex Polyurea (H 70)
   - MSDS link missing
Processing HC124: Hind Hydroflex WBPU 2K
   - MSDS link missing
Processing HC125: Hind Hydroflex Polyurea (H90)
   - MSDS link missing
Processing HC126: Hind Urethane TC
   - MSDS link missing
Processing HC127: Hind Hydro Flex PU (BM)
   - MSDS link missing
Processing HC128: Hind Coat LR 9415
   - MSDS link missing
Processing HC129: Hind Prime BIT 746
   - MSDS link missing
Processing HC130: Hind Coat Repel SC
   - MSDS link missing
Processing HC131: Hind PU CLX 650
   - MSDS link missing
Processing HC132: Hind Carbo Guard W
   - MSDS link missing
Processing HC133: Hind Geo Grout
   - MSDS link missing
Processing HC134: Hind Grout GP2
   ✓ Downloaded and extracted
Processing HC135: Hind Grout GP
   - MSDS link missing
Processing HC136: Hind Grout GP1
   - MSDS link missing
Processing HC137: Hind Hydrafoam PU (SC)
   - MSDS link missing
Processing HC138: Hind Grout SST
   - MSDS link missing
Processing HC139: Hind HSMC
   - MSDS link missing
Processing HC140: Hind Tile Grout
   - MSDS link missing
Processing HC141: Hind Plast EGA
   - MSDS link missing
Processing HC142: Hind Plast Super G
   - MSDS link missing
Processing HC143: Hind Grout GP2 (M)
   - MSDS link missing
Processing HC144: Hind Hydrafoam PU(2K)
   - MSDS link missing
Processing HC145: Hind Grout PGM
   - MSDS link missing
Processing HC146: Hind Power Grout
   - MSDS link missing
Processing HC147: Hind Grout PGM (M)
   - MSDS link missing
Processing HC148: Hind Anchorlok
   - MSDS link missing
Processing HC149: Hind EP 21
   - MSDS link missing
Processing HC150: Hind EP 321
   - MSDS link missing
Processing HC151: Hind ERA 31
   - MSDS link missing
Processing HC152: Hind ERS (UL)
   ✓ Downloaded and extracted
Processing HC153: Hind ERS 21 (LV)
   - MSDS link missing
Processing HC154: Hind ERS 21
   ✓ Downloaded and extracted
Processing HC155: Hind ERS 21 P
   - MSDS link missing
Processing HC156: Hind ERS 31 (LV)
   - MSDS link missing
Processing HC157: Hind ERS 212
   - MSDS link missing
Processing HC158: Hind ERS 216 (UV)
   - MSDS link missing
Processing HC159: Hind ERS 219
   - MSDS link missing
Processing HC160: Hind ERS-2115/2118/2120
   ✓ Downloaded and extracted
Processing HC161: Hind ERS 3116
   - MSDS link missing
Processing HC162: Hind Marbo Cote 41
   - MSDS link missing
Processing HC163: Hind EPC SLRH
   - MSDS link missing
Processing HC164: Hind ERS (UL-F)
   - MSDS link missing
Processing HC165: Hind ERS UL 800
   - MSDS link missing
Processing HC166: Hind EP Coat 236
   - MSDS link missing
Processing HC167: Hind EPZ 107
   - MSDS link missing
Processing HC168: Hind CE 750
   - MSDS link missing
Processing HC169: Hind Actcolor
   - MSDS link missing
Processing HC170: Hind Coat FC
   - MSDS link missing
Processing HC171: Hind Coat Prime
   - MSDS link missing
Processing HC172: Hind Emetop M (RTU)
   - MSDS link missing
Processing HC173: Hind Emetop M
   - MSDS link missing
Processing HC174: Hind Emetop NM
   - MSDS link missing
Processing HC175: Hind Emetop RTU
   - MSDS link missing
Processing HC176: Hind FLC E
   - MSDS link missing
Processing HC177: Hind FLC EUV
   - MSDS link missing
Processing HC178: Hind Floor FLC
   - MSDS link missing
Processing HC179: Hind Floortop
   - MSDS link missing
Processing HC180: Hind Pentro Hard LH
   - MSDS link missing
Processing HC181: Hind Polycoat
   - MSDS link missing
Processing HC182: Hind Selfloor 1000 EPSL
   - MSDS link missing
Processing HC183: Hind Selfloor 1000
   ✓ Downloaded and extracted
Processing HC184: Hind Pentro Hard NS
   - MSDS link missing
Processing HC185: Hind Cure Hard 54
   - MSDS link missing
Processing HC186: Hind ERS HBC
   - MSDS link missing
Processing HC187: Hind Selfloor 2000
   - MSDS link missing
Processing HC188: HIND ERS PRIME
   - MSDS link missing
Processing HC189: Hind Bolt C
   - MSDS link missing
Processing HC190: Hind Bolt R (Slow Set)
   - MSDS link missing
Processing HC191: Hind Bolt R
   - MSDS link missing
Processing HC192: Hind Cem (MF)
   - MSDS link missing
Processing HC193: Hind Set LAF 100
   - MSDS link missing
Processing HC194: Hind Set LAF
   ✓ Downloaded and extracted
Processing HC195: Hind Set PAF
   - MSDS link missing
Processing HC196: Hind Shot Set L
   - MSDS link missing
Processing HC197: Hind Shot Set P
   - MSDS link missing
Processing HC198: Hind Set RP (AF)
   - MSDS link missing
Processing HC199: Hind Sealant BP (HA)
   - MSDS link missing
Processing HC200: Hind Sealant BP (HA-FR)
   - MSDS link missing
Processing HC201: Hind Sealant BP
   - MSDS link missing
Processing HC202: Hind Sealant E
   - MSDS link missing
Processing HC203: Hind Sealant.PPU
   - MSDS link missing
Processing HC204: Hind Sealant Primer
   - MSDS link missing
Processing HC205: Hind Sealant PS
   - MSDS link missing
Processing HC206: Hind Sealant PU 125
   - MSDS link missing
Processing HC207: Hind Sealant PU
   - MSDS link missing
Processing HC208: Hind Silicone Sealant
   - MSDS link missing
Processing HC209: Hind Sealant PU-PG (2K)
   - MSDS link missing
Processing HC210: Hind Sealant PU 160
   - MSDS link missing
Processing HC211: Hind PU Sealer 275
   - MSDS link missing
Processing HC212: Hind ME Seal
   - MSDS link missing
Processing HC213: Hind Silicone Sealant WP 200
   - MSDS link missing
Processing HC214: Hind Silicone Sealant WP 800
   - MSDS link missing
Processing HC215: Hind Concap CP 400
   - MSDS link missing
Processing HC216: Hind Crack Seal 400
   - MSDS link missing
Processing HC217: Hind MS 9215
   - MSDS link missing
Processing HC218: Hind Sealant PU 100
   - MSDS link missing
Processing HC219: Hind Sealant PU FLEX 825
   - MSDS link missing
Processing HC220: Hind MS 40
   - MSDS link missing
Processing HC221: Hind Seal BIT 1706
   - MSDS link missing
Processing HC222: Hind Block Fix
   - MSDS link missing
Processing HC223: Hind Fix MA (W)
   - MSDS link missing
Processing HC224: Hind Fix TA (L)
   - MSDS link missing
Processing HC225: Hind Fix TA (O)
   - MSDS link missing
Processing HC226: Hind Fix TA – 1
   - MSDS link missing
Processing HC227: Hind Fix TA – 2
   - MSDS link missing
Processing HC228: Hind Grout Admix 737
   - MSDS link missing
Processing HC229: Hind Fix TA – 3
   - MSDS link missing
Processing HC230: Hind PU Masterflex
   - MSDS link missing
Processing HC231: Hind Grout Admix 747
   - MSDS link missing
Processing HC232: Hind Floor Cleaner (Neutral)
   - MSDS link missing
Processing HC233: Hind Rust Clean
   - MSDS link missing
Processing HC234: Hind Tile Clean
   - MSDS link missing
Processing HC235: Hind MUltisafe Glass & Surface Cleaner
   - MSDS link missing
Processing HC236: Hind Foundry SL
   - MSDS link missing
Processing HC237: Hind Geo Grout
   - MSDS link missing
Processing HC238: Hind Grout SST
   - MSDS link missing
Processing HC239: Hind Poly Bond
   - MSDS link missing
Processing HC240: Hind Hydroswell
   - MSDS link missing
Processing HC241: Hind Injecto Tube
   - MSDS link missing
Processing HC242: Hind Anti Rust
   - MSDS link missing
Processing HC243: Hind Block Fix
   - MSDS link missing
Processing HC244: Hind Crete Plus WPM
   - MSDS link missing
Processing HC245: Hind Crystal Seal
   - MSDS link missing
Processing HC246: Hind Fix TA
   - MSDS link missing
Processing HC247: Hind Cool Coat (formerly Hind Hydraproof Ceramic)
   - MSDS link missing
Processing HC248: Hind Hydrolast 2K
   - MSDS link missing
Processing HC249: Hind Patch R
   - MSDS link missing
Processing HC250: Hind Plast EGA
   - MSDS link missing
Processing HC251: Hind Plasto Guard
   - MSDS link missing
Processing HC252: Hind Sealant PS
   - MSDS link missing
Processing HC253: Hind Styrene BR
   - MSDS link missing
Processing HC254: Hind Tile Grout
   - MSDS link missing
Processing HC255: Hind Grind Aid 400/450/500
   - MSDS link missing
Processing HC256: Hind Emulsion A-C-P
   - MSDS link missing
Processing HC257: Hind Sol SR
   - MSDS link missing
Processing HC258: SODIUM SILICATE (NEUTRAL)
   ✓ Downloaded and extracted
Processing HC259: SODIUM SILICATE (ALKALINE)
   - MSDS link missing
Processing HC260: COLLOIDAL SILICA (CS30)
   - MSDS link missing
Processing HC261: COLLOIDAL SILICA (CS40)
   - MSDS link missing
Processing HC262: SODIUM METASILICATE 5H₂O
   - MSDS link missing
Processing HC263: SODIUM METASILICATE 9H₂O
   - MSDS link missing
Processing HC264: Multi Safe FLOOR CLEANER (Lavender)
   - MSDS link missing
Processing HC265: Multi Safe FLOOR CLEANER (Citrus)
   - MSDS link missing
Processing HC266: Multi Safe FLOOR CLEANER (Floral)
   - MSDS link missing
Processing HC267: Multi Safe FLOOR CLEANER (Neem)
   - MSDS link missing
Processing HC268: Multi Safe TILE CLEANER
   - MSDS link missing
Processing HC269: Multi Safe GLASS CLEANER
   - MSDS link missing
Processing HC270: Multi Safe RUST REMOVER
   - MSDS link missing
Processing HC271: Multi Safe TAP & SHOWER CLEANER
   ✓ Downloaded and extracted

Finished processing all MSDS files.

In [ ]:
msds_df = pd.DataFrame(msds_data)

print("Dataset shape:", msds_df.shape)

print("\nStatus:")
print(msds_df["Status"].value_counts())

Dataset shape: (271, 5)

Status:
Status
MSDS Link Missing    253
Success               18
Name: count, dtype: int64

In [ ]:
import re

def clean_text_for_excel(text):

    if pd.isna(text):
        return text

    text = str(text)

    # Remove characters that Excel cannot store
    text = re.sub(
        r'[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]',
        '',
        text
    )

    return text


msds_df["MSDS_Text"] = msds_df["MSDS_Text"].apply(
    clean_text_for_excel
)

In [ ]:
import os

os.makedirs("../output", exist_ok=True)

msds_output = "../output/msds_dataset.xlsx"

msds_df.to_excel(
    msds_output,
    index=False
)

print("MSDS dataset saved successfully!")
print("Location:", msds_output)

MSDS dataset saved successfully!
Location: ../output/msds_dataset.xlsx

In [ ]:
print("Rows:", len(msds_df))
print("Columns:", msds_df.columns.tolist())
print("File exists:", os.path.exists(msds_output))

Rows: 271
Columns: ['Product_ID', 'Product_Name', 'MSDS_Link', 'MSDS_Text', 'Status']
File exists: True

In [80]:
import pandas as pd
import os

products_df = pd.read_excel("../output/products_dataset.xlsx")
tds_df = pd.read_excel("../output/tds_dataset.xlsx")
msds_df = pd.read_excel("../output/msds_dataset.xlsx")

print("Products:", products_df.shape)
print("TDS:", tds_df.shape)
print("MSDS:", msds_df.shape)

Products: (271, 5)
TDS: (271, 5)
MSDS: (271, 5)

In [81]:
tds_master = tds_df[
    [
        "Product_ID",
        "TDS_Link",
        "TDS_Text",
        "Status"
    ]
].copy()

tds_master = tds_master.rename(
    columns={
        "Status": "TDS_Status"
    }
)

In [82]:
msds_master = msds_df[
    [
        "Product_ID",
        "MSDS_Link",
        "MSDS_Text",
        "Status"
    ]
].copy()

msds_master = msds_master.rename(
    columns={
        "Status": "MSDS_Status"
    }
)

In [83]:
master_df = products_df.merge(
    tds_master,
    on="Product_ID",
    how="left"
)

In [84]:
master_df = master_df.merge(
    msds_master,
    on="Product_ID",
    how="left"
)

In [86]:
print(master_df.columns.tolist())

['Product_ID', 'Category', 'Product_Name', 'TDS_Link_x', 'MSDS_Link_x', 'TDS_Link_y', 'TDS_Text', 'TDS_Status', 'MSDS_Link_y', 'MSDS_Text', 'MSDS_Status']

In [87]:
import pandas as pd

# Load the three datasets
products_df = pd.read_excel("../output/products_dataset.xlsx")
tds_df = pd.read_excel("../output/tds_dataset.xlsx")
msds_df = pd.read_excel("../output/msds_dataset.xlsx")

# Keep only TDS information that is not already in products_df
tds_master = tds_df[
    ["Product_ID", "TDS_Text", "Status"]
].copy()

tds_master = tds_master.rename(
    columns={"Status": "TDS_Status"}
)

# Keep only MSDS information that is not already in products_df
msds_master = msds_df[
    ["Product_ID", "MSDS_Text", "Status"]
].copy()

msds_master = msds_master.rename(
    columns={"Status": "MSDS_Status"}
)

# Merge TDS data
master_df = products_df.merge(
    tds_master,
    on="Product_ID",
    how="left"
)

# Merge MSDS data
master_df = master_df.merge(
    msds_master,
    on="Product_ID",
    how="left"
)

# Arrange columns
master_df = master_df[
    [
        "Product_ID",
        "Category",
        "Product_Name",
        "TDS_Link",
        "TDS_Text",
        "TDS_Status",
        "MSDS_Link",
        "MSDS_Text",
        "MSDS_Status"
    ]
]

# Check result
print("Master dataset shape:", master_df.shape)
print("\nColumns:")
print(master_df.columns.tolist())

# Save
master_df.to_excel(
    "../output/hindcon_master_dataset.xlsx",
    index=False
)

print("\nMaster dataset created successfully!")

Master dataset shape: (271, 9)

Columns:
['Product_ID', 'Category', 'Product_Name', 'TDS_Link', 'TDS_Text', 'TDS_Status', 'MSDS_Link', 'MSDS_Text', 'MSDS_Status']

Master dataset created successfully!